#!/bin/sh

# Set perms
find / -exec chown root: {} \;
find / -type d -exec chmod 0755 {} \;
find /bin /sbin /usr -type f -exec chmod 0755 {} \;
find /etc -type f -exec chmod 0644 {} \;
mv /System.map /home/user
chown user: /home/user -R

# Mount points
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
chmod 0444 /proc/slabinfo

# Share
mkdir -p /mnt/
mount -t 9p -o trans=virtio mountpoint /mnt/ -oversion=9p2000.L,posixacl,sync
chmod 777 /mnt/

# Insert module
insmod /vuln.ko

# Shell
cat /etc/issue
export ENV=/etc/profile
setsid cttyhack setuidgid 1000 sh

poweroff -f
